name = "announcement-app"
client_id = "bb3d6b0ead17ab318c0b0b9f40d19611"
application_url = "https://almost-keys-guests-conflicts.trycloudflare.com"
embedded = true

[access_scopes]
scopes = "write_metaobjects,read_metaobjects"

[auth]
redirect_urls = [" https://almost-keys-guests-conflicts.trycloudflare.com/auth/callback", " https://almost-keys-guests-conflicts.trycloudflare.com/auth/shopify/callback", " https://almost-keys-guests-conflicts.trycloudflare.com/exitiframe"]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
